//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace IdentiGo.ExternalServices.WsProspectaPlusTest {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ProspectaPlusSoapBinding", Namespace="http://prospecta.webservice.com")]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(InconsistenciasDTO))]
    public partial class ProspectaPlusWSService : Microsoft.Web.Services3.WebServicesClientProtocol
    {
        
        private System.Threading.SendOrPostCallback consultaProspectaOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ProspectaPlusWSService() {
            this.Url = global::IdentiGo.ExternalServices.Properties.Settings.Default.IdentiGo_ExternalServices_WsProspectaPlusTest_ProspectaPlusWSService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event consultaProspectaCompletedEventHandler consultaProspectaCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://prospecta.webservice.com", ResponseNamespace="http://prospecta.webservice.com")]
        [return: System.Xml.Serialization.SoapElementAttribute("consultaProspectaReturn")]
        public RespuestaProspectaDTO consultaProspecta(string codigoInformacion, string numeroIdentificacion, string tipoIdentificacion) {
            object[] results = this.Invoke("consultaProspecta", new object[] {
                        codigoInformacion,
                        numeroIdentificacion,
                        tipoIdentificacion});
            return ((RespuestaProspectaDTO)(results[0]));
        }
        
        /// <remarks/>
        public void consultaProspectaAsync(string codigoInformacion, string numeroIdentificacion, string tipoIdentificacion) {
            this.consultaProspectaAsync(codigoInformacion, numeroIdentificacion, tipoIdentificacion, null);
        }
        
        /// <remarks/>
        public void consultaProspectaAsync(string codigoInformacion, string numeroIdentificacion, string tipoIdentificacion, object userState) {
            if ((this.consultaProspectaOperationCompleted == null)) {
                this.consultaProspectaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnconsultaProspectaOperationCompleted);
            }
            this.InvokeAsync("consultaProspecta", new object[] {
                        codigoInformacion,
                        numeroIdentificacion,
                        tipoIdentificacion}, this.consultaProspectaOperationCompleted, userState);
        }
        
        private void OnconsultaProspectaOperationCompleted(object arg) {
            if ((this.consultaProspectaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.consultaProspectaCompleted(this, new consultaProspectaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://dto.prospecta.webservice.com")]
    public partial class RespuestaProspectaDTO {
        
        private System.Nullable<bool> consultadaRecienteField;
        
        private System.Nullable<bool> generoInconsistenciasField;
        
        private InconsistenciasDTO[] inconsistenciasField;
        
        private string nombreTitularField;
        
        private string numeroIdentificacionField;
        
        private string resultadoField;
        
        private string tipoIdentificacionField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<bool> consultadaReciente {
            get {
                return this.consultadaRecienteField;
            }
            set {
                this.consultadaRecienteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<bool> generoInconsistencias {
            get {
                return this.generoInconsistenciasField;
            }
            set {
                this.generoInconsistenciasField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public InconsistenciasDTO[] inconsistencias {
            get {
                return this.inconsistenciasField;
            }
            set {
                this.inconsistenciasField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string nombreTitular {
            get {
                return this.nombreTitularField;
            }
            set {
                this.nombreTitularField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string numeroIdentificacion {
            get {
                return this.numeroIdentificacionField;
            }
            set {
                this.numeroIdentificacionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string resultado {
            get {
                return this.resultadoField;
            }
            set {
                this.resultadoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string tipoIdentificacion {
            get {
                return this.tipoIdentificacionField;
            }
            set {
                this.tipoIdentificacionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://dto.prospecta.webservice.com")]
    public partial class InconsistenciasDTO {
        
        private string codigoField;
        
        private string descripcionField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void consultaProspectaCompletedEventHandler(object sender, consultaProspectaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class consultaProspectaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal consultaProspectaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RespuestaProspectaDTO Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RespuestaProspectaDTO)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591