//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace IdentiGo.ExternalServices.WsNombraAvon {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="NombraAvonServiceSoapBinding", Namespace="http://131.0.168.230:8080/NombraAvonQA/services/NombraAvonService")]
    public partial class AvonServiceEndPointService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ValidarPagoContadoOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConsultarCedulaOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConsultarGZSLOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConsultarCodigoOperationCompleted;
        
        private System.Threading.SendOrPostCallback CargarSAFOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public AvonServiceEndPointService() {
            this.Url = global::IdentiGo.ExternalServices.Properties.Settings.Default.IdentiGo_ExternalServices_WsNombraAvon_AvonServiceEndPointService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ValidarPagoContadoCompletedEventHandler ValidarPagoContadoCompleted;
        
        /// <remarks/>
        public event ConsultarCedulaCompletedEventHandler ConsultarCedulaCompleted;
        
        /// <remarks/>
        public event ConsultarGZSLCompletedEventHandler ConsultarGZSLCompleted;
        
        /// <remarks/>
        public event ConsultarCodigoCompletedEventHandler ConsultarCodigoCompleted;
        
        /// <remarks/>
        public event CargarSAFCompletedEventHandler CargarSAFCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://ws.sapian.com", ResponseNamespace="http://131.0.168.230:8080/NombraAvonQA/services/NombraAvonService")]
        [return: System.Xml.Serialization.SoapElementAttribute("ValidarPagoContadoReturn")]
        public int ValidarPagoContado(int cedula, string genero, string riesgo, int fec_Nacimiento, int division, int zona, int unidad) {
            object[] results = this.Invoke("ValidarPagoContado", new object[] {
                        cedula,
                        genero,
                        riesgo,
                        fec_Nacimiento,
                        division,
                        zona,
                        unidad});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void ValidarPagoContadoAsync(int cedula, string genero, string riesgo, int fec_Nacimiento, int division, int zona, int unidad) {
            this.ValidarPagoContadoAsync(cedula, genero, riesgo, fec_Nacimiento, division, zona, unidad, null);
        }
        
        /// <remarks/>
        public void ValidarPagoContadoAsync(int cedula, string genero, string riesgo, int fec_Nacimiento, int division, int zona, int unidad, object userState) {
            if ((this.ValidarPagoContadoOperationCompleted == null)) {
                this.ValidarPagoContadoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnValidarPagoContadoOperationCompleted);
            }
            this.InvokeAsync("ValidarPagoContado", new object[] {
                        cedula,
                        genero,
                        riesgo,
                        fec_Nacimiento,
                        division,
                        zona,
                        unidad}, this.ValidarPagoContadoOperationCompleted, userState);
        }
        
        private void OnValidarPagoContadoOperationCompleted(object arg) {
            if ((this.ValidarPagoContadoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ValidarPagoContadoCompleted(this, new ValidarPagoContadoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://ws.sapian.com", ResponseNamespace="http://131.0.168.230:8080/NombraAvonQA/services/NombraAvonService")]
        [return: System.Xml.Serialization.SoapElementAttribute("ConsultarCedulaReturn")]
        public Result ConsultarCedula(string parameter1, string parameter2, string parameter3) {
            object[] results = this.Invoke("ConsultarCedula", new object[] {
                        parameter1,
                        parameter2,
                        parameter3});
            return ((Result)(results[0]));
        }
        
        /// <remarks/>
        public void ConsultarCedulaAsync(string parameter1, string parameter2, string parameter3) {
            this.ConsultarCedulaAsync(parameter1, parameter2, parameter3, null);
        }
        
        /// <remarks/>
        public void ConsultarCedulaAsync(string parameter1, string parameter2, string parameter3, object userState) {
            if ((this.ConsultarCedulaOperationCompleted == null)) {
                this.ConsultarCedulaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultarCedulaOperationCompleted);
            }
            this.InvokeAsync("ConsultarCedula", new object[] {
                        parameter1,
                        parameter2,
                        parameter3}, this.ConsultarCedulaOperationCompleted, userState);
        }
        
        private void OnConsultarCedulaOperationCompleted(object arg) {
            if ((this.ConsultarCedulaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultarCedulaCompleted(this, new ConsultarCedulaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://ws.sapian.com", ResponseNamespace="http://131.0.168.230:8080/NombraAvonQA/services/NombraAvonService")]
        [return: System.Xml.Serialization.SoapElementAttribute("ConsultarGZSLReturn")]
        public Result ConsultarGZSL(string parameter1, string parameter2, string parameter3) {
            object[] results = this.Invoke("ConsultarGZSL", new object[] {
                        parameter1,
                        parameter2,
                        parameter3});
            return ((Result)(results[0]));
        }
        
        /// <remarks/>
        public void ConsultarGZSLAsync(string parameter1, string parameter2, string parameter3) {
            this.ConsultarGZSLAsync(parameter1, parameter2, parameter3, null);
        }
        
        /// <remarks/>
        public void ConsultarGZSLAsync(string parameter1, string parameter2, string parameter3, object userState) {
            if ((this.ConsultarGZSLOperationCompleted == null)) {
                this.ConsultarGZSLOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultarGZSLOperationCompleted);
            }
            this.InvokeAsync("ConsultarGZSL", new object[] {
                        parameter1,
                        parameter2,
                        parameter3}, this.ConsultarGZSLOperationCompleted, userState);
        }
        
        private void OnConsultarGZSLOperationCompleted(object arg) {
            if ((this.ConsultarGZSLCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultarGZSLCompleted(this, new ConsultarGZSLCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://ws.sapian.com", ResponseNamespace="http://131.0.168.230:8080/NombraAvonQA/services/NombraAvonService")]
        [return: System.Xml.Serialization.SoapElementAttribute("ConsultarCodigoReturn")]
        public Result ConsultarCodigo(string parameter1, string parameter2, string parameter3) {
            object[] results = this.Invoke("ConsultarCodigo", new object[] {
                        parameter1,
                        parameter2,
                        parameter3});
            return ((Result)(results[0]));
        }
        
        /// <remarks/>
        public void ConsultarCodigoAsync(string parameter1, string parameter2, string parameter3) {
            this.ConsultarCodigoAsync(parameter1, parameter2, parameter3, null);
        }
        
        /// <remarks/>
        public void ConsultarCodigoAsync(string parameter1, string parameter2, string parameter3, object userState) {
            if ((this.ConsultarCodigoOperationCompleted == null)) {
                this.ConsultarCodigoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultarCodigoOperationCompleted);
            }
            this.InvokeAsync("ConsultarCodigo", new object[] {
                        parameter1,
                        parameter2,
                        parameter3}, this.ConsultarCodigoOperationCompleted, userState);
        }
        
        private void OnConsultarCodigoOperationCompleted(object arg) {
            if ((this.ConsultarCodigoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultarCodigoCompleted(this, new ConsultarCodigoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://ws.sapian.com", ResponseNamespace="http://131.0.168.230:8080/NombraAvonQA/services/NombraAvonService")]
        [return: System.Xml.Serialization.SoapElementAttribute("CargarSAFReturn")]
        public Result CargarSAF(string parameter1, string parameter2, string parameter3, string parameter4, string parameter5, string parameter6, string parameter7) {
            object[] results = this.Invoke("CargarSAF", new object[] {
                        parameter1,
                        parameter2,
                        parameter3,
                        parameter4,
                        parameter5,
                        parameter6,
                        parameter7});
            return ((Result)(results[0]));
        }
        
        /// <remarks/>
        public void CargarSAFAsync(string parameter1, string parameter2, string parameter3, string parameter4, string parameter5, string parameter6, string parameter7) {
            this.CargarSAFAsync(parameter1, parameter2, parameter3, parameter4, parameter5, parameter6, parameter7, null);
        }
        
        /// <remarks/>
        public void CargarSAFAsync(string parameter1, string parameter2, string parameter3, string parameter4, string parameter5, string parameter6, string parameter7, object userState) {
            if ((this.CargarSAFOperationCompleted == null)) {
                this.CargarSAFOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCargarSAFOperationCompleted);
            }
            this.InvokeAsync("CargarSAF", new object[] {
                        parameter1,
                        parameter2,
                        parameter3,
                        parameter4,
                        parameter5,
                        parameter6,
                        parameter7}, this.CargarSAFOperationCompleted, userState);
        }
        
        private void OnCargarSAFOperationCompleted(object arg) {
            if ((this.CargarSAFCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CargarSAFCompleted(this, new CargarSAFCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:NombraAvon")]
    public partial class Result {
        
        private string errorCodeField;
        
        private string output1Field;
        
        private string output10Field;
        
        private string output11Field;
        
        private string output12Field;
        
        private string output13Field;
        
        private string output14Field;
        
        private string output15Field;
        
        private string output2Field;
        
        private string output3Field;
        
        private string output4Field;
        
        private string output5Field;
        
        private string output6Field;
        
        private string output7Field;
        
        private string output8Field;
        
        private string output9Field;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string errorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string output1 {
            get {
                return this.output1Field;
            }
            set {
                this.output1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string output10 {
            get {
                return this.output10Field;
            }
            set {
                this.output10Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string output11 {
            get {
                return this.output11Field;
            }
            set {
                this.output11Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string output12 {
            get {
                return this.output12Field;
            }
            set {
                this.output12Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string output13 {
            get {
                return this.output13Field;
            }
            set {
                this.output13Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string output14 {
            get {
                return this.output14Field;
            }
            set {
                this.output14Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string output15 {
            get {
                return this.output15Field;
            }
            set {
                this.output15Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string output2 {
            get {
                return this.output2Field;
            }
            set {
                this.output2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string output3 {
            get {
                return this.output3Field;
            }
            set {
                this.output3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string output4 {
            get {
                return this.output4Field;
            }
            set {
                this.output4Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string output5 {
            get {
                return this.output5Field;
            }
            set {
                this.output5Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string output6 {
            get {
                return this.output6Field;
            }
            set {
                this.output6Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string output7 {
            get {
                return this.output7Field;
            }
            set {
                this.output7Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string output8 {
            get {
                return this.output8Field;
            }
            set {
                this.output8Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string output9 {
            get {
                return this.output9Field;
            }
            set {
                this.output9Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void ValidarPagoContadoCompletedEventHandler(object sender, ValidarPagoContadoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ValidarPagoContadoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ValidarPagoContadoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void ConsultarCedulaCompletedEventHandler(object sender, ConsultarCedulaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultarCedulaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultarCedulaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Result Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Result)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void ConsultarGZSLCompletedEventHandler(object sender, ConsultarGZSLCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultarGZSLCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultarGZSLCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Result Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Result)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void ConsultarCodigoCompletedEventHandler(object sender, ConsultarCodigoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultarCodigoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultarCodigoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Result Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Result)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void CargarSAFCompletedEventHandler(object sender, CargarSAFCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CargarSAFCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CargarSAFCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Result Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Result)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591