// <auto-generated />
namespace IdentiGo.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class update30 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(update30));
        
        string IMigrationMetadata.Id
        {
            get { return "201903010440373_update30"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
