//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace IdentiGo.ExternalServices.WsInformacionComercial {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="InformacionComercialSoapBinding", Namespace="http://infocomercial.cifin.asobancaria.com")]
    public partial class InformacionComercialWSService : Microsoft.Web.Services3.WebServicesClientProtocol
    {
        
        private System.Threading.SendOrPostCallback consultaXmlOperationCompleted;
        
        private System.Threading.SendOrPostCallback consultaPlanoOperationCompleted;
        
        private System.Threading.SendOrPostCallback cambioPasswordOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public InformacionComercialWSService() {
            this.Url = global::IdentiGo.ExternalServices.Properties.Settings.Default.IdentiGo_ExternalServices_WsInformacionComercial_InformacionComercialWSService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event consultaXmlCompletedEventHandler consultaXmlCompleted;
        
        /// <remarks/>
        public event consultaPlanoCompletedEventHandler consultaPlanoCompleted;
        
        /// <remarks/>
        public event cambioPasswordCompletedEventHandler cambioPasswordCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://infocomercial.cifin.asobancaria.com", ResponseNamespace="http://infocomercial.cifin.asobancaria.com")]
        [return: System.Xml.Serialization.SoapElementAttribute("consultaXmlReturn")]
        public string consultaXml(ParametrosConsultaDTO parametrosConsulta) {
            object[] results = this.Invoke("consultaXml", new object[] {
                        parametrosConsulta});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void consultaXmlAsync(ParametrosConsultaDTO parametrosConsulta) {
            this.consultaXmlAsync(parametrosConsulta, null);
        }
        
        /// <remarks/>
        public void consultaXmlAsync(ParametrosConsultaDTO parametrosConsulta, object userState) {
            if ((this.consultaXmlOperationCompleted == null)) {
                this.consultaXmlOperationCompleted = new System.Threading.SendOrPostCallback(this.OnconsultaXmlOperationCompleted);
            }
            this.InvokeAsync("consultaXml", new object[] {
                        parametrosConsulta}, this.consultaXmlOperationCompleted, userState);
        }
        
        private void OnconsultaXmlOperationCompleted(object arg) {
            if ((this.consultaXmlCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.consultaXmlCompleted(this, new consultaXmlCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://infocomercial.cifin.asobancaria.com", ResponseNamespace="http://infocomercial.cifin.asobancaria.com")]
        [return: System.Xml.Serialization.SoapElementAttribute("consultaPlanoReturn")]
        public string consultaPlano(ParametrosConsultaDTO parametrosConsulta) {
            object[] results = this.Invoke("consultaPlano", new object[] {
                        parametrosConsulta});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void consultaPlanoAsync(ParametrosConsultaDTO parametrosConsulta) {
            this.consultaPlanoAsync(parametrosConsulta, null);
        }
        
        /// <remarks/>
        public void consultaPlanoAsync(ParametrosConsultaDTO parametrosConsulta, object userState) {
            if ((this.consultaPlanoOperationCompleted == null)) {
                this.consultaPlanoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnconsultaPlanoOperationCompleted);
            }
            this.InvokeAsync("consultaPlano", new object[] {
                        parametrosConsulta}, this.consultaPlanoOperationCompleted, userState);
        }
        
        private void OnconsultaPlanoOperationCompleted(object arg) {
            if ((this.consultaPlanoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.consultaPlanoCompleted(this, new consultaPlanoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://infocomercial.cifin.asobancaria.com", ResponseNamespace="http://infocomercial.cifin.asobancaria.com")]
        [return: System.Xml.Serialization.SoapElementAttribute("cambioPasswordReturn")]
        public string cambioPassword(string nuevoPassword) {
            object[] results = this.Invoke("cambioPassword", new object[] {
                        nuevoPassword});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void cambioPasswordAsync(string nuevoPassword) {
            this.cambioPasswordAsync(nuevoPassword, null);
        }
        
        /// <remarks/>
        public void cambioPasswordAsync(string nuevoPassword, object userState) {
            if ((this.cambioPasswordOperationCompleted == null)) {
                this.cambioPasswordOperationCompleted = new System.Threading.SendOrPostCallback(this.OncambioPasswordOperationCompleted);
            }
            this.InvokeAsync("cambioPassword", new object[] {
                        nuevoPassword}, this.cambioPasswordOperationCompleted, userState);
        }
        
        private void OncambioPasswordOperationCompleted(object arg) {
            if ((this.cambioPasswordCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.cambioPasswordCompleted(this, new cambioPasswordCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://dto.infocomercial.cifin.asobancaria.com")]
    public partial class ParametrosConsultaDTO {
        
        private string numeroIdentificacionField;
        
        private string motivoConsultaField;
        
        private string tipoIdentificacionField;
        
        private string codigoInformacionField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string numeroIdentificacion {
            get {
                return this.numeroIdentificacionField;
            }
            set {
                this.numeroIdentificacionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string motivoConsulta {
            get {
                return this.motivoConsultaField;
            }
            set {
                this.motivoConsultaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string tipoIdentificacion {
            get {
                return this.tipoIdentificacionField;
            }
            set {
                this.tipoIdentificacionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string codigoInformacion {
            get {
                return this.codigoInformacionField;
            }
            set {
                this.codigoInformacionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void consultaXmlCompletedEventHandler(object sender, consultaXmlCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class consultaXmlCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal consultaXmlCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void consultaPlanoCompletedEventHandler(object sender, consultaPlanoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class consultaPlanoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal consultaPlanoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void cambioPasswordCompletedEventHandler(object sender, cambioPasswordCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class cambioPasswordCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal cambioPasswordCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591