//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IdentiGo.ExternalServices.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.8.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://cifin.asobancaria.com/InformacionComercialWS/services/InformacionComercial" +
            "")]
        public string IdentiGo_ExternalServices_WsInformacionComercial_InformacionComercialWSService {
            get {
                return ((string)(this["IdentiGo_ExternalServices_WsInformacionComercial_InformacionComercialWSService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://cifin.asobancaria.com/ws/ProspectaWebService/services/Prospecta")]
        public string IdentiGo_ExternalServices_WsProspecta_ProspectaWSService {
            get {
                return ((string)(this["IdentiGo_ExternalServices_WsProspecta_ProspectaWSService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://131.0.168.230:8080/NombraAvonQA/services/NombraAvonService")]
        public string IdentiGo_ExternalServices_WsNombraAvon_AvonServiceEndPointService {
            get {
                return ((string)(this["IdentiGo_ExternalServices_WsNombraAvon_AvonServiceEndPointService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://ttuweb3.universo.corp/ws/ProspectaPlusWebService/services/ProspectaPlus")]
        public string IdentiGo_ExternalServices_WsProspectaPlusTest_ProspectaPlusWSService {
            get {
                return ((string)(this["IdentiGo_ExternalServices_WsProspectaPlusTest_ProspectaPlusWSService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://cifin.asobancaria.com/ws/ProspectaPlusWebService/services/ProspectaPlus")]
        public string IdentiGo_ExternalServices_WsProspectaPlus_ProspectaPlusWSService {
            get {
                return ((string)(this["IdentiGo_ExternalServices_WsProspectaPlus_ProspectaPlusWSService"]));
            }
        }
    }
}
